import type { DriverSignature } from "./types";

/**
 * Known agent drivers and the identifiers they leave in a page.
 *
 * `activeDom`, `windowGlobals`, `messageTypes` and `declaredUserAgent` mean an agent is acting.
 * `presence`, `navigatorProps`, `userAgent` and `brands` only mean a product is installed; they name a driver
 * once behaviour already says an agent is driving, and never move the verdict.
 *
 * Every identifier is a moving target. Keep `sources`, `confidence` and `verifiedVersion` current.
 * Last research pass: 2026-10-07.
 */

const CLAUDE = "https://github.com/ContextFort-AI/ContextFort";
const CHEQ = "https://cheq.ai/blog/the-cyborg-session-reversing-detecting-claude-ai-agent-chrome-extension/";
const CASTLE = "https://blog.castle.io/from-detection-to-trust-the-evolving-challenge-of-ai-bot-authentication/";
const HUMAN_SEC = "https://www.humansecurity.com/learn/blog/chatgpt-atlas-vs-perplexity-comet-agentic-browsers/";
const FP_AGENT = "https://arxiv.org/abs/2605.01247";
const TOPSHOP = "https://github.com/asafev/TopShop";

export const DRIVERS: DriverSignature[] = [
  // ───────────────────────── Extension agents (drive the user's own browser) ─────────────────────────
  {
    id: "claude-in-chrome",
    name: "Claude in Chrome",
    provider: "Anthropic",
    kind: "extension",
    activeDom: {
      ids: [
        "claude-agent-glow-border",
        "claude-agent-glow-border-inner",
        "claude-agent-stop-container",
        "claude-agent-stop-button",
        "claude-phantom-cursor",
        "claude-phantom-cursor-plain",
        "claude-phantom-cursor-styled",
        "claude-static-indicator-container",
      ],
      classes: ["claude-agent-glow-border"],
    },
    styleIds: ["claude-agent-animation-styles"],
    keyframes: ["claude-pulse"],
    extensionIds: ["fcoeoabgfenejglbffodgkkbkcdhcgfn", "dihbgbndebgnbjfmelmegjepbnkhlgni", "dngcpimnedloihjnnfngkgjoidhnaolf"],
    mechanics: {
      hoverMs: [80, 130],
      pressMs: [0, 16],
      keyGapMs: [0, 2],
      keyHoldMs: [0, 2],
      typing: "keys",
      scroll: "wheel-100",
      clickCentre: true,
      teleports: true,
    },
    confidence: "source",
    sources: [CLAUDE, CHEQ, "https://github.com/youseiushida/agent-in-chrome", "https://chromewebstore.google.com/detail/claude/fcoeoabgfenejglbffodgkkbkcdhcgfn"],
    notes:
      "chrome.debugger (CDP 1.3), attached for the whole session. Click (1.0.36): hide overlays → 50 ms → one mouseMoved → 100 ms → mousePressed → 12 ms → mouseReleased; 1.0.90+ skips the delays when its UI is not foregrounded and sends force 0.5. " +
      "Typing: ASCII as CDP keyDown/keyUp with no delay (Promise.all from 1.0.90), capitals with shiftKey but no Shift keydown; Input.insertText only for unmapped characters. " +
      "form_input sets value in the isolated world, then fires untrusted change BEFORE input. Scroll: one mouseWheel of ticks×100 px, falling back to scrollBy (no wheel) and always in background tabs. " +
      "MCP mode (Claude Code/Desktop/Cowork) shows the glow and cursor but no stop button. The animation <style> is never removed. Clones (claw-in-chrome, codex-in-chrome) reuse the same ids.",
    verifiedVersion: "1.0.36 source; 1.0.90–1.0.94 teardowns",
  },
  {
    id: "chatgpt-extension",
    name: "ChatGPT for Chrome / Codex",
    provider: "OpenAI",
    kind: "extension",
    activeDom: {
      ids: ["codex-agent-overlay-root"],
      attributes: ["data-codex-agent-overlay-root", "data-codex-favicon-badge", "data-codex-original-favicon-href"],
    },
    windowGlobals: ["__codexAgentPopupInterceptor", "__browserUseClipboardBridge"],
    messageTypes: ["^[a-p]{32}:codex:wxt:content-script-started$", "^[a-p]{32}:codex:wxt:locationchange$"],
    extensionIds: ["hehggadaopoacecdllhhajmbjkdcmajg", "odlomjlbamekndcpllcnffbgeohgkmjh", "lfkehkpjohcoelkpembgemeipeppanef"],
    mechanics: { pressMs: [0, 3], typing: "synthetic-paste", scroll: "gesture", clickCentre: true, teleports: true },
    confidence: "source",
    sources: ["https://github.com/iFurySt/open-browser-use", "https://learn.chatgpt.com/docs/chrome-extension", "https://github.com/wxt-dev/wxt"],
    notes:
      "Raw CDP pipe driven by the desktop app's browser-service. Click: mouseMoved → mousePressed → mouseReleased with no delay and no force (pressure 0). " +
      "Typing: an untrusted ClipboardEvent('paste') then the prototype value setter and an untrusted InputEvent with inputType ''; no key events. Scroll: synthesizeScrollGesture at speed 8000. " +
      "Focus emulation keeps background tabs reporting focus. Agent tabs get a favicon badge and a closed-shadow overlay root. Requests from leased tabs may carry 'x-browser-agent: ChatGPT/<sessionId>' (server-side).",
    verifiedVersion: "content script 1.1.5; browser-service 26.915",
  },
  {
    id: "chatgpt-desktop",
    name: "ChatGPT / Codex desktop browser",
    provider: "OpenAI",
    kind: "agentic-browser",
    presence: { dom: { ids: ["codex-browser-sidebar-comments-root"] }, windowGlobals: ["__codexWebMcpModelContext"] },
    mechanics: { pressMs: [0, 3], typing: "synthetic-paste", teleports: true },
    confidence: "source",
    sources: ["https://github.com/JimLiu/decode-codex", "https://github.com/openai/codex"],
    notes: "Electron webview driven over webContents.debugger with the same browser-service as the extension. The comments root and WebMCP bridge exist whether or not the agent acts. Network sec-ch-ua is rewritten; compare the header with navigator.userAgentData server-side.",
  },
  {
    id: "manus-operator",
    name: "Manus Browser Operator",
    provider: "Manus",
    kind: "extension",
    activeDom: { ids: ["manus-action-mask-host"], attributes: ["data-manus_clickable", "data-manus_click_id"] },
    presence: { dom: { attributes: ["manus-helper-ready"] }, windowGlobals: ["__manusOriginalPostMessage"] },
    consoleMarkers: ["Manus helper started"],
    extensionIds: ["cecngibhkljoiafhjfmcgbmikfogdiko", "mljmkmodkfigdopcpgboaalildgijkoc"],
    mechanics: { keyGapMs: [0.5, 3], typing: "keys", teleports: true },
    confidence: "secondary",
    sources: ["https://manus.im/docs/features/browser-operator", FP_AGENT, TOPSHOP],
    notes: "CDP via the debugger permission. ~1.4 ms between keys and ~53 ms holds (FP-Agent). Monica's operator also writes data-manus_click_id; Monica is told apart by #monica-action-mask-host.",
  },
  {
    id: "monica",
    name: "Monica operator",
    provider: "Monica (Butterfly Effect)",
    kind: "extension",
    activeDom: { ids: ["monica-action-mask-host"] },
    presence: { dom: { ids: ["monica-content-root"], attributes: ["monica-id"] } },
    extensionIds: ["ofpnmcalabcbjgholdjcjblkibolbppb", "fhimbbbmdjiifimnepkibjfjbppnjble"],
    confidence: "source",
    sources: ["https://chromewebstore.google.com/detail/ofpnmcalabcbjgholdjcjblkibolbppb"],
    notes: "Overlay text 'Monica is browsing...', keyframes effect-pulse. Clicks are a single untrusted MouseEvent('click') with no down/up.",
  },
  {
    id: "openclaw",
    name: "OpenClaw",
    provider: "OpenClaw",
    kind: "extension",
    activeDom: {
      ids: ["__openclaw-annotations__"],
      attributes: ["data-openclaw-browser-ref", "data-openclaw-cdp-ci", "data-openclaw-labels", "data-openclaw-mcp-overlay"],
    },
    extensionIds: ["kcdjddhmeafeomebliikmbpblkmkfoig", "naeanbdjhgjchiopliicmcokmcpdjool", "bobkbcmgacnlomccmnaglobifoljcghb"],
    mechanics: { pressMs: [0, 3], typing: "insert-bulk", clickCentre: true, teleports: true },
    confidence: "source",
    sources: ["https://github.com/openclaw/openclaw", "https://docs.claw.so/engine/tools/chrome-extension/"],
    notes: "Browser Relay: Playwright over chrome.debugger. One mouseMoved to the centre, press/release with 0 delay; fill = select-all + one Input.insertText; 'slowly' = keys every 75 ms. data-openclaw-browser-ref persists until the next snapshot.",
  },
  {
    id: "genspark",
    name: "Genspark",
    provider: "Genspark",
    kind: "extension",
    activeDom: { ids: ["gs-overlay-cursor-style"] },
    presence: { dom: { ids: ["genspark-float-bar"] } },
    navigatorProps: ["genspark"],
    userAgent: ["Genspark/[\\d.]+"],
    extensionIds: ["hmdkfngkncmbgiehonfebecighedjiak"],
    confidence: "secondary",
    sources: [TOPSHOP],
    notes: "navigator.genspark identifies the Genspark AI Browser. Uses the debugger permission, so probably CDP input.",
  },
  {
    id: "nanobrowser",
    name: "Nanobrowser",
    provider: "Nanobrowser",
    kind: "extension",
    activeDom: { ids: ["puppeteer-disable-animations"], classes: ["playwright-highlight-label"] },
    extensionIds: ["imbddededgmcgfhfpcjmijokokekbkal"],
    mechanics: { pressMs: [0, 3], keyHoldMs: [45, 55], typing: "keys", scroll: "no-wheel", clickCentre: true, teleports: true },
    confidence: "source",
    sources: ["https://github.com/nanobrowser/nanobrowser"],
    notes:
      "Puppeteer over chrome.debugger. Injects a main-world anti-detection script (navigator.webdriver getter → undefined, window.chrome stub, non-native navigator.permissions.query, attachShadow forced open). " +
      "Typing clears with untrusted input/change, then keys held exactly 50 ms; <select> fires change then input; scroll with scrollBy. Shares #playwright-highlight-container with the browser-use family.",
  },
  {
    id: "browseros",
    name: "BrowserOS",
    provider: "BrowserOS",
    kind: "agentic-browser",
    activeDom: {
      ids: ["browseros-glow-overlay", "browseros-glow-stop-btn", "browseros-glow-styles"],
      tags: ["browseros-neo-takeover", "browseros-pointer"],
      attributes: ["data-__bcid", "data-browseros-screenshot-annotation"],
    },
    keyframes: ["browseros-glow-pulse", "browseros-glow-fade-in"],
    extensionIds: ["bflpfmnmnokmjhmgnolecpppdbdophmk", "djhdjhlnljbjgejbndockeedocneiaei", "pjimfkbpehlcllblajnpfamdfjhhlgkc", "nlnihljpboknmfagkikhkdblbedophja"],
    mechanics: { pressMs: [0, 3], typing: "insert-bulk", teleports: true },
    confidence: "source",
    sources: ["https://github.com/browseros-ai/BrowserOS"],
    notes: "Chromium fork with component extensions; uses the browser's own CDP, so no debugger infobar.",
  },
  {
    id: "taxy",
    name: "Taxy AI",
    provider: "Taxy",
    kind: "extension",
    activeDom: { attributes: ["data-taxy-node-id"] },
    presence: { cssProbes: [{ className: "web-agent-ripple", expect: { animationName: "web-agent-ripple" } }] },
    mechanics: { keyGapMs: [45, 55], typing: "keys", teleports: true },
    confidence: "source",
    sources: ["https://github.com/TaxyAI/browser-extension"],
    notes: "Clicks are mousePressed/mouseReleased with no mouseMoved. Keys carry only text (empty key and code) at 50 ms gaps. Disables Dashlane and LastPass while running.",
  },
  {
    id: "multion",
    name: "MultiOn",
    provider: "MultiOn",
    kind: "extension",
    activeDom: { idPrefixes: ["multion-root-", "multion-popup-"], attributes: ["multion-container"] },
    extensionIds: ["ddmjhdbknfidiopmbaceghhhbgbpenmm"],
    confidence: "secondary",
    sources: ["https://chromewebstore.google.com/detail/ddmjhdbknfidiopmbaceghhhbgbpenmm"],
    notes: "Removed from the Chrome Web Store on 2025-09-15; existing installs remain.",
  },
  {
    id: "hyperwrite",
    name: "HyperWrite",
    provider: "Otherside AI",
    kind: "extension",
    presence: { dom: { ids: ["otherside-root", "hyper-main-container", "hyper-menu-shadow-root", "assistant-shadow-root"] } },
    extensionIds: ["kljjoeapehcmaphfcjkmbhkinoaopdnd"],
    mechanics: { typing: "value-set" },
    confidence: "source",
    sources: ["https://chromewebstore.google.com/detail/kljjoeapehcmaphfcjkmbhkinoaopdnd"],
    notes: "Acts through @testing-library/user-event: untrusted pointer, mouse and key sequences at 0 ms.",
  },
  {
    id: "harpa",
    name: "HARPA AI",
    provider: "HARPA",
    kind: "extension",
    presence: { dom: { tags: ["__hrp__"] }, windowGlobals: ["__hrp_globals", "__app_hrp", "__hrpc"] },
    extensionIds: ["eanggfilgoajaocelnaflolkadkeghjp"],
    mechanics: { keyGapMs: [15, 25], typing: "keys" },
    confidence: "source",
    sources: ["https://chromewebstore.google.com/detail/eanggfilgoajaocelnaflolkadkeghjp"],
    notes: "Globals and the <__hrp__> element are present whenever HARPA is installed, not only while it automates. Synthetic pointer/mouse events 50 ms apart; 20 ms key gaps.",
  },
  {
    id: "do-browser",
    name: "Do Browser",
    provider: "Do Browser",
    kind: "extension",
    messageTypes: ["^hjcibkpfgnljonndnnanhkholafmgmip:content:wxt:content-script-started$"],
    extensionIds: ["hjcibkpfgnljonndnnanhkholafmgmip"],
    confidence: "source",
    sources: ["https://chromewebstore.google.com/detail/hjcibkpfgnljonndnnanhkholafmgmip"],
    notes: "Puppeteer; typing starts with clickCount 4; scroll with scrollBy. Cursor is an unnamed closed-shadow div labelled 'Do Browser'.",
  },
  {
    id: "sider",
    name: "Sider agent",
    provider: "Sider",
    kind: "extension",
    presence: { dom: { tags: ["chatgpt-sidebar"] } },
    messageTypes: ["^clickAt$", "^pressKeyChord$", "^scrollWheel$"],
    extensionIds: ["difoiogjjojoaoomphldepapgpbgkhkb", "dhoenijjpgpeimemopealfcbiecgceod"],
    mechanics: { typing: "value-set" },
    confidence: "source",
    sources: ["https://chromewebstore.google.com/detail/difoiogjjojoaoomphldepapgpbgkhkb"],
    notes: "Agent glow #sider-agent-glow-border lives inside the open shadow of <chatgpt-sidebar>. Input via user-event (untrusted).",
  },
  {
    id: "bardeen",
    name: "Bardeen",
    provider: "Bardeen",
    kind: "extension",
    activeDom: { attributes: ["data-bardeen-agent-action"] },
    presence: { dom: { ids: ["bardeen-root"] } },
    extensionIds: ["ihhkmalpkhkoedlmcnilbbhhbhnicjga"],
    confidence: "source",
    sources: ["https://chromewebstore.google.com/detail/ihhkmalpkhkoedlmcnilbbhhbhnicjga"],
    notes: "Untrusted mousedown → click → mouseup (wrong order).",
  },
  {
    id: "midscene",
    name: "Midscene",
    provider: "ByteDance",
    kind: "framework",
    windowGlobals: ["midscene_element_inspector", "midsceneNodeHashCache", "midsceneGenerateHash", "midsceneVisibleRect", "midsceneWaterFlowAnimation", "__MIDSCENE_NEW_TAB_INTERCEPTOR_INITIALIZED__"],
    activeDom: { ids: ["water-flow-animation"], attributes: ["data-water-flow-pointer"] },
    consoleMarkers: ["Blocked window.open:"],
    keyframes: ["waterflow"],
    extensionIds: ["gbldofcpkknbggpkmbdaefngejllnief"],
    confidence: "source",
    sources: ["https://github.com/web-infra-dev/midscene"],
  },
  {
    id: "skyvern",
    name: "Skyvern",
    provider: "Skyvern",
    kind: "framework",
    windowGlobals: [
      "GlobalSkyvernFrameIndex",
      "GlobalEnableAllTextualElements",
      "globalOneTimeIncrementElements",
      "globalDomDepthMap",
      "globalListnerFlag",
      "globalObserverForDOMIncrement",
      "globalHoverStylesMap",
      "globalParsedElementCounter",
      "globalIncrementalJobCount",
      "buildElementsAndDrawBoundingBoxes",
      "removeAllUniqueIds",
      "__PW_CURSOR_VIS__",
      "__pw_trails",
    ],
    activeDom: { tags: ["skyvern-control-indicator"], ids: ["boundingBoxContainer", "__pw-cursor"], attributes: ["data-skyvern-otp-box", "data-skyvern-otp-filled", "data-pw-overlay"] },
    extensionIds: ["dhommdmblflboaledbbfkdaapkadphlp"],
    mechanics: { keyGapMs: [8, 13], typing: "keys", screens: ["1920x1080"] },
    confidence: "source",
    sources: ["https://github.com/Skyvern-AI/skyvern", FP_AGENT],
    notes: "Indicator text 'Skyvern is controlling this tab'. ~9.5 ms between keys; instant scroll-into-view.",
  },
  {
    id: "page-agent",
    name: "page-agent",
    provider: "Alibaba",
    kind: "extension",
    activeDom: { ids: ["page-agent-runtime_simulator-mask"] },
    extensionIds: ["akldabonmimlicnjlflnapfeklbfemhj"],
    confidence: "source",
    sources: ["https://github.com/alibaba/page-agent"],
  },
  {
    id: "aipex",
    name: "AIPex",
    provider: "AIPex",
    kind: "extension",
    activeDom: { ids: ["aipex-border-overlay"] },
    presence: { dom: { ids: ["aipex-content-root"] } },
    keyframes: ["aipexBreathe"],
    extensionIds: ["iglkpadagfelcpmiidndgjgafpdifnke"],
    confidence: "source",
    sources: ["https://chromewebstore.google.com/detail/iglkpadagfelcpmiidndgjgafpdifnke"],
  },
  {
    id: "thunderbit",
    name: "Thunderbit",
    provider: "Thunderbit",
    kind: "extension",
    activeDom: { ids: ["thunderbit-crx-scout-overlay"] },
    presence: { dom: { ids: ["thunderbit-crx-side-bar"] } },
    confidence: "secondary",
    sources: [TOPSHOP],
  },
  {
    id: "rtrvr",
    name: "rtrvr.ai",
    provider: "rtrvr.ai",
    kind: "extension",
    extensionIds: ["jldogdgepmcedfdhgnmclgemehfhpomg"],
    confidence: "secondary",
    sources: [TOPSHOP],
    notes: "Writes rtrvr-* attributes on <html>.",
  },
  {
    id: "kimi-webbridge",
    name: "Kimi WebBridge",
    provider: "Moonshot AI",
    kind: "extension",
    extensionIds: ["fldmhceldgbpfpkbgopacenieobmligc"],
    confidence: "secondary",
    sources: [TOPSHOP],
    notes: "Clicks are untrusted element.click().",
  },
  {
    id: "playwright-mcp",
    name: "Playwright MCP extension",
    provider: "Microsoft",
    kind: "extension",
    extensionIds: ["mmlmfjhmonkocbjadbfplnigmagldckm", "jakfalbnbhgkpmoaakfflhflbfpkailf"],
    mechanics: { hoverMs: [0, 5], pressMs: [0, 3], typing: "insert-bulk", clickCentre: true, teleports: true },
    confidence: "source",
    sources: ["https://github.com/microsoft/playwright-mcp"],
    notes: "No content scripts or web-accessible resources. Click sends move/press/release together with force 0.5; fill = select() + one Input.insertText; every injected call uses userGesture:true.",
  },
  {
    id: "browser-mcp",
    name: "Browser MCP",
    provider: "Browser MCP",
    kind: "extension",
    extensionIds: ["bjfgambnhccakkhmkepdoekmckoijdlc"],
    confidence: "secondary",
    sources: ["https://browsermcp.io/"],
  },
  {
    id: "chrome-devtools-mcp",
    name: "Chrome DevTools MCP",
    provider: "Google",
    kind: "framework",
    builtOn: "puppeteer",
    // Puppeteer's source URLs carry the caller's location: pptr:evaluateHandle;WaitForHelper.waitForStableDom%20(file%3A…%2Fchrome-devtools-mcp%2Fbuild%2Fsrc%2Futils%2FWaitForHelper.js…)
    stackMarkers: ["pptr:evaluateHandle;WaitForHelper.waitForStableDom", "chrome-devtools-mcp%2Fbuild%2Fsrc"],
    windowGlobals: ["__dtmcp"],
    mechanics: { pressMs: [0, 3], clickCentre: true, teleports: true, screens: ["3840x2160"] },
    confidence: "lab",
    verifiedVersion: "1.10.1 (bundled Puppeteer, Chrome 154)",
    sources: ["https://github.com/ChromeDevTools/chrome-devtools-mcp/blob/main/src/utils/WaitForHelper.ts", "https://github.com/ChromeDevTools/chrome-devtools-mcp/blob/main/src/BrowserManager.ts"],
    notes:
      "Built on Puppeteer, so Puppeteer's __ariaQuerySelector globals and its clicks (pressure 0, ~1 ms presses) and key-by-key typing appear too. Its own marker is in stack traces: after every action it starts a main-world MutationObserver from pptr:evaluateHandle;WaitForHelper.waitForStableDom, whose source URL holds the chrome-devtools-mcp path. Headless runs report a 3840×2160 screen (--screen-info). Focus emulation is always on. __dtmcp appears only with the experimental third-party tools category.",
  },
  {
    id: "mcp-chrome",
    name: "mcp-chrome",
    provider: "hangwin",
    kind: "extension",
    messageTypes: ["^rr-bridge-"],
    extensionIds: ["hbdgbgagpkpjffpklnamcljpakneikee"],
    confidence: "source",
    sources: ["https://github.com/hangwin/mcp-chrome"],
    notes: "Default click is an untrusted MouseEvent with screenX 0 and no pointer events.",
  },
  {
    id: "kapture",
    name: "Kapture",
    provider: "Kapture",
    kind: "extension",
    activeDom: { ids: ["kapture-cursor"], classes: ["kapture-connected"] },
    presence: { dom: { classes: ["kapture-loaded"] } },
    extensionIds: ["ejfnegenodbdcodemkibocefmajjjjbn"],
    confidence: "source",
    sources: ["https://github.com/williamkapke/kapture"],
  },
  {
    id: "browsertools-mcp",
    name: "BrowserTools MCP",
    provider: "AgentDesk",
    kind: "extension",
    presence: { windowGlobals: ["__btmcpInstalled", "__btmcpBuffer"] },
    confidence: "source",
    sources: ["https://github.com/AgentDeskAI/browser-tools-mcp"],
  },
  {
    id: "agent-browser",
    name: "Vercel agent-browser",
    provider: "Vercel",
    kind: "framework",
    // `find text|label|placeholder|testid|nth` tags the target for a few ms; the recording cursor only exists while recording.
    activeDom: { attributes: ["data-agent-browser-located", "data-agent-browser-recording-cursor"] },
    // It launches Chrome with --enable-features=WebMCPTesting. Only a hint while stable Chrome ships WebMCP off; drop it once WebMCP is on by default.
    presence: { windowGlobals: ["ModelContext", "WebMCPEvent"] },
    mechanics: { pressMs: [0, 3], typing: "insert-bulk", clickCentre: true, teleports: true },
    confidence: "lab",
    verifiedVersion: "0.38.2 (Chrome 154)",
    sources: ["https://github.com/vercel-labs/agent-browser"],
    notes:
      "A Rust CLI over raw CDP, not Puppeteer or Playwright. Launches Chrome with WebMCP testing on, so window.ModelContext exists. fill: an untrusted input event on the cleared field, then the whole string in one trusted insertText, no key presses. select fires only an untrusted change event. Clicks: CDP mouse events at the centre, pressure 0. find text/label/placeholder tags the target with data-agent-browser-located for a few ms; snapshot refs and CSS selectors leave nothing in the DOM.",
  },

  // ───────────────────────── Agentic browsers and built-in agents ─────────────────────────
  {
    id: "gemini-in-chrome",
    name: "Gemini in Chrome (auto browse)",
    provider: "Google",
    kind: "built-in-agent",
    mechanics: {
      hoverMs: [3, 9],
      pressMs: [3, 9],
      keyGapMs: [40, 60],
      keyHoldMs: [20, 30],
      typing: "keys",
      scroll: "no-wheel",
      clickCentre: true,
      teleports: true,
    },
    confidence: "source",
    sources: [
      "https://chromium.googlesource.com/chromium/src/+/main/chrome/renderer/actor/click_dispatcher.cc",
      "https://chromium.googlesource.com/chromium/src/+/main/chrome/renderer/actor/type_tool.cc",
      "https://chromium.googlesource.com/chromium/src/+/main/chrome/renderer/actor/scroll_tool.cc",
      "https://chromium.googlesource.com/chromium/src/+/main/chrome/common/chrome_features.cc",
    ],
    notes:
      "Chromium actor (M153+ defaults; Finch can change them): one mousemove → 5 ms → mousedown → 5 ms → mouseup at the integer centre of the first client rect. Hover/move events never set a screen position (screenX 0 with clientX > 0). " +
      "Typing: SelectAll with no Ctrl+A, keydown+char in one task, keyup 25 ms later, next key 25 ms after (≈50 ms; ≈10 ms above 45 chars; paste above 200 chars with a trusted paste event and no Ctrl+V). Capitals carry shiftKey with no Shift keydown. " +
      "Scroll via scrollTo: no wheel. Select via SetValue: trusted input/change with no focus or pointer. Occluded targets get an accessibility click (no move, offsetX/offsetY 0, pressure 0). Forces focus and visibility on a background tab while acting. Nothing is injected into the page.",
    verifiedVersion: "M157 main (2026-10-07)",
  },
  {
    id: "brave-leo",
    name: "Brave Leo AI browsing",
    provider: "Brave",
    kind: "built-in-agent",
    brands: ["Brave"],
    navigatorProps: ["brave"],
    mechanics: { hoverMs: [3, 9], pressMs: [3, 9], keyGapMs: [40, 60], keyHoldMs: [20, 30], typing: "keys", scroll: "no-wheel", clickCentre: true, teleports: true },
    confidence: "source",
    sources: ["https://github.com/brave/brave-core/tree/master/browser/ai_chat", "https://brave.com/blog/ai-browsing/"],
    notes: "Same Chromium actor as Gemini in Chrome, in an isolated 'AI browsing' profile (no user cookies).",
  },
  {
    id: "comet",
    name: "Perplexity Comet",
    provider: "Perplexity",
    kind: "agentic-browser",
    activeDom: { idPrefixes: ["pplx-agent-"], ids: ["pplx-agent-overlay", "pplx-agent-overlay-stop-button"] },
    presence: { cssProbes: [{ id: "pplx-agent-0_0-overlay-stop-button", expect: { zIndex: "2147483647", minHeight: "32px" } }] },
    extensionIds: ["npclhjbddhklpbnacpjloidibaggcgon", "mcjlamohcooanphmebaiigheeeoplihb", "pninphncmkphpjgfffammoenglghcjii"],
    mechanics: { pressMs: [0, 6], typing: "paste", teleports: true },
    confidence: "teardown",
    sources: [CASTLE, HUMAN_SEC, "https://labs.zenity.io/post/perplexity-comet-a-reversing-story", FP_AGENT],
    notes:
      "Hidden comet-agent extension drives the page through chrome.debugger with no mousemove before clicks; pasted text; page reading via the accessibility tree. While active it swallows trusted user input. " +
      "Overlay ids are pplx-agent-0_0-overlay(-base|-stop-button) (legacy pplx-agent-overlay); an overlay frame loads from the agent extension. Comet's CSS is on every page, so a planted stop-button element reveals the browser even with no task running. No Comet brand in client hints.",
  },
  {
    id: "edge-copilot",
    name: "Edge Copilot Mode",
    provider: "Microsoft",
    kind: "built-in-agent",
    brands: ["Microsoft Edge"],
    confidence: "docs",
    sources: ["https://learn.microsoft.com/en-us/deployedge/microsoft-edge-management-browsing-with-copilot"],
    notes: "Nothing injected into the page; inserts several characters per event (~16 chars/s). The brand identifies Edge, not that Copilot is acting.",
  },
  {
    id: "opera-neon",
    name: "Opera Neon",
    provider: "Opera",
    kind: "agentic-browser",
    brands: ["Opera", "Opera GX"],
    userAgent: ["\\bOPR/"],
    confidence: "secondary",
    sources: ["https://blogs.opera.com/news/2025/05/opera-neon-first-ai-agentic-browser/"],
    notes: "Brand identifies Opera, not that the agent is acting. Neon's own UA and brand were not found.",
  },
  {
    id: "atlas",
    name: "ChatGPT Atlas (retired)",
    provider: "OpenAI",
    kind: "agentic-browser",
    presence: { windowGlobals: ["ChatGPTBrowser"] },
    mechanics: { typing: "paste", teleports: true },
    confidence: "secondary",
    sources: ["https://techcrunch.com/2026/07/09/openai-is-shutting-down-atlas-but-its-ai-browser-ambitions-are-still-growing/", HUMAN_SEC],
    notes: "Shut down 9 Aug 2026. Input went straight to the renderer (trusted, no injection); stock Chrome UA and brands.",
  },
  {
    id: "sigma",
    name: "Sigma AI browser",
    provider: "Sigma",
    kind: "agentic-browser",
    presence: { windowGlobals: ["__SIGMA__"], dom: { ids: ["__gradient_border_wrapper__"] }, styleIds: ["sigma-translation-styles"] },
    confidence: "secondary",
    sources: [TOPSHOP],
    notes: "Agent mode bundles OpenClaw and Hermes.",
  },
  {
    id: "fellou",
    name: "Fellou",
    provider: "Fellou",
    kind: "agentic-browser",
    presence: { windowGlobals: ["__FELLOU_TAB_ID__"] },
    confidence: "secondary",
    sources: [TOPSHOP],
    notes: "Agent framework is Eko (see 'eko').",
  },
  {
    id: "antigravity",
    name: "Google Antigravity browser",
    provider: "Google",
    kind: "agentic-browser",
    presence: { dom: { attributes: ["data-jetski-tab-id"] } },
    confidence: "secondary",
    sources: [TOPSHOP],
  },
  {
    id: "cursor-browser",
    name: "Cursor IDE browser",
    provider: "Anysphere",
    kind: "agentic-browser",
    presence: { windowGlobals: ["__cursorDialogConfig"] },
    confidence: "secondary",
    sources: [TOPSHOP],
  },

  // ───────────────────────── Frameworks and cloud browsers ─────────────────────────
  {
    id: "browser-use",
    name: "browser-use",
    provider: "Browser Use",
    kind: "framework",
    activeDom: {
      ids: ["playwright-highlight-container", "browser-use-debug-highlights", "browser-use-demo-panel", "browser-use-demo-toggle", "browser-use-demo-panel-style"],
      attributes: ["data-browser-use-interaction-highlight", "data-browser-use-coordinate-highlight", "data-browser-use-highlight", "browser-user-highlight-id"],
    },
    windowGlobals: ["__browserUseDemoPanelLoaded"],
    consoleMarkers: ["browser-use highlight elements", "=== BROWSER-USE HIGHLIGHTING ==="],
    mechanics: { hoverMs: [40, 70], pressMs: [70, 95], keyGapMs: [0.5, 8], typing: "keys", scroll: "gesture", clickCentre: true, teleports: true, screens: ["1920x1080"] },
    confidence: "source",
    sources: ["https://github.com/browser-use/browser-use/blob/main/browser_use/browser/watchdogs/default_action_watchdog.py"],
    notes:
      "v0.13: CDP without Runtime.enable. Click: scrollIntoViewIfNeeded → 50 ms → mouseMoved → 50 ms → mousePressed → 80 ms → mouseReleased at the quad centre. Typing: DOM.focus, clear via native setter + untrusted input/change, then per char keyDown → 5 ms → char → keyUp (~1 ms gaps), then an untrusted InputEvent, change and blur. Page scroll: synthesizeScrollGesture at speed 50000. Before each screenshot logs 'Removing N browser-use highlight elements'. Strips --enable-automation (webdriver false). #playwright-highlight-container and browser-user-highlight-id come from its buildDomTree script, which Nanobrowser, Monica, page-agent, UI-TARS and old Eko reuse.",
  },
  {
    id: "stagehand",
    name: "Stagehand / Browserbase",
    provider: "Browserbase",
    kind: "cloud-browser",
    windowGlobals: ["__stagehandV3Injected", "__stagehandV3__", "__stagehandInjected", "__stagehand__", "__v3Cursor", "__updateCursorPosition", "__animateClick"],
    activeDom: {
      ids: ["__v3_cursor_overlay__", "stagehand-cursor", "stagehand-highlight"],
      attributes: ["data-stagehand-style", "data-stagehand-mask", "data-stagehand-mask-root", "data-stagehand-mask-root-pos"],
    },
    consoleMarkers: ["[v3-piercer]"],
    mechanics: { hoverMs: [0, 5], pressMs: [0, 3], typing: "insert-bulk", clickCentre: true, teleports: true, screens: ["1280x800"] },
    confidence: "source",
    sources: ["https://github.com/browserbase/stagehand/blob/main/packages/extension/understudy/locator.ts"],
    notes:
      "v3 patches Element.prototype.attachShadow and logs '[v3-piercer] installed'; v2's stealth script sets the non-standard navigator.headless and fakes navigator.plugins. click() pipelines move + press + release (~0 ms) at the box centre; fill() = Backspace then Input.insertText. v4 moves to an isolated-world extension. Browserbase signs requests with Web Bot Auth (directory www.browserbase.com).",
  },
  {
    id: "ui-tars",
    name: "UI-TARS",
    provider: "ByteDance",
    kind: "framework",
    activeDom: { ids: ["gui-agent-helper-styles", "gui-agent-water-flow"] },
    confidence: "source",
    sources: ["https://github.com/bytedance/UI-TARS-desktop"],
  },
  {
    id: "playwright",
    name: "Playwright",
    provider: "Microsoft",
    kind: "framework",
    windowGlobals: [
      "__playwright__binding__",
      "__playwright__binding__controller__",
      "__pwInitScripts",
      "__pwClock",
      "__pwWebAuthnBinding",
      "__pw_recorderState",
      "__pw_recorderPerformAction",
      "__pw_recorderRecordAction",
      "__pw_resume",
      "__pw_refreshOverlay",
      "__pw_bidiInsertText",
      "__pwSnapshotGlobals",
    ],
    activeDom: {
      tags: [
        "x-pw-glass",
        "x-pw-highlight",
        "x-pw-tooltip",
        "x-pw-tooltip-line",
        "x-pw-action-point",
        "x-pw-action-cursor",
        "x-pw-title",
        "x-pw-user-overlays",
        "x-pw-screencast-highlight",
        "x-pw-screencast-point",
      ],
    },
    stackMarkers: ["__playwright_evaluation_script__", "UtilityScript.evaluate", "UtilityScript.<anonymous>", "__playwright_utility_world_"],
    mechanics: { hoverMs: [0, 5], pressMs: [0, 3], typing: "insert-bulk", clickCentre: true, teleports: true, screens: ["1280x720"] },
    confidence: "source",
    sources: ["https://github.com/microsoft/playwright/blob/main/packages/playwright-core/src/server/input.ts", "https://github.com/microsoft/playwright/issues/41873"],
    notes:
      "1.53+ injects no globals by default (1.48–1.52 put __playwright__binding__ on every page; 1.46–1.52 __pwInitScripts). --remote-debugging-pipe sets webdriver. Focus emulation makes document.hasFocus() true even in hidden tabs. Click: one move to the centre, press (force 0.5) and release together. fill = Input.insertText; fill on date/color/range and selectOption = plain untrusted Event('input'/'change'). Headless default 1280×720, chromium-headless-shell UA/brands say HeadlessChrome.",
  },
  {
    id: "puppeteer",
    name: "Puppeteer",
    provider: "Google",
    kind: "framework",
    windowGlobals: ["__ariaQuerySelector", "__ariaQuerySelectorAll", "puppeteer___ariaQuerySelector", "puppeteer___ariaQuerySelectorAll"],
    stackMarkers: ["__puppeteer_evaluation_script__", "pptr:evaluate", "pptr:internal", "pptr://"],
    mechanics: { pressMs: [0, 3], clickCentre: true, teleports: true, screens: ["800x600"] },
    confidence: "source",
    sources: ["https://github.com/puppeteer/puppeteer", "https://blog.crawlex.net/blog/kasada-anti-instrumentation/"],
    notes: "exposeFunction adds window.puppeteer_<name> CDP bindings (found by the binding scan). --enable-automation sets webdriver. Default viewport 800×600; mouse events carry pressure 0; type = keyDown(text)+keyUp with no delay; sourceURL pptr:<fn>;<caller> (20.2+) leaks the caller's file path.",
  },
  {
    id: "selenium",
    name: "Selenium / ChromeDriver",
    provider: "Selenium",
    kind: "framework",
    windowGlobals: [
      "_Selenium_IDE_Recorder",
      "_selenium",
      "callSelenium",
      "__webdriver_script_fn",
      "__webdriver_evaluate",
      "__selenium_evaluate",
      "__webdriver_unwrapped",
      "__selenium_unwrapped",
      "__fxdriver_evaluate",
      "__driver_evaluate",
      "__webdriverFunc",
      "domAutomation",
      "domAutomationController",
      "$cdc_asdjflasutopfhvcZLmcfl_",
      "cdc_adoQpoasnfa76pfcZLmcfl_Array",
      "cdc_adoQpoasnfa76pfcZLmcfl_Object",
      "cdc_adoQpoasnfa76pfcZLmcfl_Promise",
      "cdc_adoQpoasnfa76pfcZLmcfl_Proxy",
      "cdc_adoQpoasnfa76pfcZLmcfl_Symbol",
      "cdc_adoQpoasnfa76pfcZLmcfl_JSON",
      "cdc_adoQpoasnfa76pfcZLmcfl_Window",
    ],
    consoleMarkers: ["undetected chromedriver 1337!"],
    documentGlobals: ["$cdc_asdjflasutopfhvcZLmcfl_", "$chrome_asyncScriptInfo", "__webdriver_script_fn", "__driver_unwrapped"],
    confidence: "source",
    sources: ["https://blog.crawlex.net/blog/kasada-anti-instrumentation/", "https://api.switchfrog.com/sdk/v1.js"],
  },
  {
    id: "webdriverio",
    name: "WebdriverIO",
    provider: "OpenJS",
    kind: "framework",
    builtOn: "selenium",
    // Its BiDi preload script (on by default since v9) wraps these built-ins with code that logs "[WDIO]".
    wrapperMarkers: ["[WDIO]"],
    // __wdio_sinon only with emulate('clock'); __wdio_element only when an element is passed as a selector.
    windowGlobals: ["__wdio_element", "__wdio_sinon"],
    // The wrappers log only when the page attaches a shadow root.
    consoleMarkers: ["[WDIO]"],
    // esbuild's name helper, defined before every script it runs. Generic, so a naming hint only.
    presence: { windowGlobals: ["__name"] },
    confidence: "lab",
    verifiedVersion: "10.0.0 over BiDi (ChromeDriver, Chrome 154)",
    sources: ["https://github.com/webdriverio/webdriverio/blob/main/packages/webdriverio/src/scripts/customElement.ts", "https://github.com/webdriverio/webdriverio/blob/main/packages/webdriverio/src/scripts/polyfill.ts"],
    notes:
      "Drives Chrome through ChromeDriver, so ChromeDriver's cdc_ globals (listed under Selenium) and its clicks and typing appear too. Its own marker: a BiDi preload script replaces Element.prototype.attachShadow and customElements.define with wrappers that log \"[WDIO]\", readable from page start. It also defines a global __name helper. Scrolls into view with one large trusted wheel step.",
  },
  {
    id: "cypress",
    name: "Cypress",
    provider: "Cypress.io",
    kind: "framework",
    windowGlobals: ["Cypress", "__cypress"],
    confidence: "source",
    sources: ["https://docs.cypress.io/"],
    notes: "Usually the customer's own end-to-end tests: allow-list rather than block.",
  },
  {
    id: "phantomjs",
    name: "PhantomJS",
    provider: "PhantomJS",
    kind: "framework",
    windowGlobals: ["_phantom", "callPhantom"],
    declaredUserAgent: ["PhantomJS"],
    confidence: "source",
    sources: ["https://api.switchfrog.com/sdk/v1.js"],
  },
  {
    id: "nightmare",
    name: "Nightmare",
    provider: "Segment",
    kind: "framework",
    windowGlobals: ["__nightmare"],
    confidence: "source",
    sources: ["https://api.switchfrog.com/sdk/v1.js"],
  },
  {
    id: "headless-chrome",
    name: "Headless Chrome",
    provider: "Google",
    kind: "framework",
    declaredUserAgent: ["HeadlessChrome"],
    mechanics: { screens: ["800x600"] },
    confidence: "source",
    sources: ["https://developer.chrome.com/docs/chromium/headless"],
    notes: "chrome-headless-shell also lists a HeadlessChrome brand in userAgentData; new headless keeps the UA token but not the brand. Default screen 800×600 with availHeight equal to height.",
  },
  {
    id: "nova-act",
    name: "Amazon Nova Act",
    provider: "Amazon",
    kind: "framework",
    declaredUserAgent: [" Agent-NovaAct/[\\d.]+"],
    activeDom: { attributes: ["nova-act-id"] },
    mechanics: { hoverMs: [0, 5], pressMs: [0, 3], keyGapMs: [90, 110], typing: "keys", clickCentre: true, teleports: true, screens: ["1600x900"] },
    confidence: "source",
    sources: ["https://github.com/aws/nova-act"],
    notes:
      "When it launches the browser itself the UA is the headless UA with ' Agent-NovaAct/x' appended (not when attached over CDP, e.g. AgentCore). Clicks at the exact centre with 0 ms delay; text over 10 chars uses insert_text (no keys), shorter text keyboard.type with 100 ms gaps. Fires untrusted pointerout/mouseleave after scrolling.",
  },
  {
    id: "fara",
    name: "Microsoft Fara",
    provider: "Microsoft",
    kind: "framework",
    windowGlobals: ["MultimodalWebSurfer"],
    activeDom: { ids: ["red-cursor"], attributes: ["__elementId"] },
    mechanics: { pressMs: [8, 14], typing: "keys", screens: ["1440x900"], clickCentre: true, teleports: true },
    confidence: "source",
    sources: ["https://github.com/microsoft/fara"],
    notes: "Playwright with a hard-coded Edg/122 UA (Fara-7B runs on Firefox, so the UA claims Edge without userAgentData). Viewport 1440×900. mouse.click(delay=10); typing at 0 ms (Fara 1.5) or 100 ms per char (Fara-7B).",
  },
  {
    id: "magentic-ui",
    name: "Microsoft Magentic-UI",
    provider: "Microsoft",
    kind: "framework",
    windowGlobals: ["WebSurfer"],
    confidence: "source",
    sources: ["https://github.com/microsoft/magentic-ui"],
    notes: "Same web-surfer stack as Fara (also writes __elementId attributes), global window.WebSurfer.",
  },
  {
    id: "eko",
    name: "Eko (Fellou)",
    provider: "Fellou",
    kind: "framework",
    windowGlobals: ["clickable_elements", "get_clickable_elements", "get_highlight_element", "remove_highlight"],
    minGlobalMatches: 2,
    activeDom: { ids: ["eko-highlight-container"], classes: ["eko-highlight-label"], attributes: ["eko-user-highlight-id"] },
    mechanics: { typing: "value-set" },
    confidence: "source",
    sources: ["https://github.com/FellouAI/eko"],
    notes: "Extension/web hosts dispatch untrusted mousedown/mouseup with clientX 0 then element.click(); hover is a bubbling mouseenter (real browsers never bubble it). Typing: native setter + one input event; select fires a non-bubbling change; scroll uses scrollBy.",
  },
  {
    id: "google-agent",
    name: "Google-Agent (cloud)",
    provider: "Google",
    kind: "cloud-browser",
    declaredUserAgent: ["compatible; Google-Agent"],
    confidence: "docs",
    sources: ["https://developers.google.com/crawling/docs/crawlers-fetchers/google-user-triggered-fetchers"],
    notes: "Cloud agents on Google infrastructure. Some requests are signed with Web Bot Auth (Signature-Agent g=\"https://agent.bot.goog\"); verify at the edge.",
  },
  {
    id: "meta-muse",
    name: "Meta Muse",
    provider: "Meta",
    kind: "cloud-browser",
    mechanics: { teleports: true },
    confidence: "secondary",
    sources: ["https://research.meta.ai/blog/security-and-safety-for-ai-agents-our-approach-with-muse"],
    notes: "Cloud Chromium (plain Chrome/153 on Linux) driven by a CDP broker, exiting through Cloudflare/Fastly ranges, unsigned. Not the meta-externalagent crawler UA. Expected to adopt the Personal Agent Protocol.",
  },
  {
    id: "chatgpt-agent",
    name: "ChatGPT agent (cloud browser)",
    provider: "OpenAI",
    kind: "cloud-browser",
    mechanics: { typing: "paste", screens: ["1280x960"], teleports: true },
    confidence: "secondary",
    sources: ["https://arxiv.org/abs/2606.30119", "https://help.openai.com/en/articles/11845367-chatgpt-agent-allowlisting"],
    notes: "Now ChatGPT Work's cloud browser. Signs requests (Signature-Agent \"https://chatgpt.com\", legacy string form); verify at the edge rather than in the page.",
  },
  {
    id: "patchright",
    name: "Patchright",
    provider: "Kaliiiiiiiiii-Vinyzu",
    kind: "framework",
    mechanics: { hoverMs: [0, 5], pressMs: [0, 3], typing: "insert-bulk", clickCentre: true, teleports: true },
    confidence: "source",
    sources: ["https://github.com/Kaliiiiiiiiii-Vinyzu/patchright"],
    notes:
      "Undetected Playwright fork: no Runtime.enable, isolated-world evaluate. With init scripts it rewrites HTML to insert a self-removing <script class=\"<40 hex>\" id=\"<44 hex>\"> at the end of <head> and adds 'unsafe-eval' plus a nonce to the CSP (pattern-matched by the artifact watcher). Keeps Playwright's input traits.",
  },
  {
    id: "nodriver",
    name: "nodriver",
    provider: "ultrafunkamsterdam",
    kind: "framework",
    keyframes: ["show-pointer-ani"],
    mechanics: { pressMs: [0, 3], typing: "insert-bulk", scroll: "gesture", teleports: true },
    confidence: "source",
    sources: ["https://github.com/ultrafunkamsterdam/nodriver"],
    notes:
      "No Runtime.enable and a fixed debugging port (webdriver false). Element.click() is an untrusted el.click() preceded by a 500 ms red dot div#<16 hex> with z-index 99999999 (pattern-matched); @keyframes show-pointer-ani persists in a stylesheet. mouse_click = press + release with no move; send_keys = 'char' events only (no keydown/keyup); scroll gesture at speed 7777.",
  },
  {
    id: "rebrowser",
    name: "rebrowser-patches",
    provider: "rebrowser",
    kind: "framework",
    confidence: "source",
    sources: ["https://github.com/rebrowser/rebrowser-patches"],
    notes: "Default addBinding mode leaves a random 10–20 char CDP binding on window (found by the binding scan); evaluated code carries sourceURL app.js. Unmaintained since May 2025.",
  },
  {
    id: "steel",
    name: "Steel browser",
    provider: "Steel",
    kind: "cloud-browser",
    activeDom: { ids: ["__cursor__"], tags: ["puppeteer-mouse-pointer"] },
    mechanics: { screens: ["1920x1080"] },
    confidence: "source",
    sources: ["https://github.com/steel-dev/steel-browser"],
    notes: "Fingerprint injection replaces console.debug, Object.keys, Object.getOwnPropertyNames, getContext and Worker in the main world (caught by the integrity probe); WebGL strings differ between the main thread and workers.",
  },
  {
    id: "lavague",
    name: "LaVague",
    provider: "LaVague",
    kind: "framework",
    windowGlobals: ["_lavague_move_listener"],
    activeDom: { classes: ["lavague-highlight"] },
    confidence: "source",
    sources: ["https://github.com/lavague-ai/LaVague"],
    notes: "Patches EventTarget.prototype.addEventListener and defines window.getEventListeners (normally DevTools-only). Hard-coded Chrome/107 Windows UA; 1080×1080.",
  },
  {
    id: "agent-e",
    name: "Agent-E",
    provider: "EmergenceAI",
    kind: "framework",
    windowGlobals: ["dom_mutation_change_detected", "overlay_state_changed", "show_steps_state_changed", "user_response"],
    minGlobalMatches: 2,
    activeDom: {
      ids: ["agente-overlay", "AgentEOverlayBorder", "agente-closebutton", "AgentEExpandedAnimation", "agente-chat-box"],
      classes: ["agente-ui-automation-highlight"],
      attributes: ["mmid", "orig-aria-keyshortcuts"],
    },
    confidence: "source",
    sources: ["https://github.com/EmergenceAI/Agent-E"],
    notes: "Clicks with untrusted element.click(); keyboard.type delay 1 ms.",
  },
  {
    id: "agentql",
    name: "AgentQL",
    provider: "TinyFish",
    kind: "framework",
    activeDom: { attributes: ["tf623_id"] },
    confidence: "source",
    sources: ["https://pypi.org/project/agentql/"],
    notes: "Tags elements with tf623_id and iframe_path, sets window.domUpdateObserver and leaves localStorage key lastDomChange.",
  },
  {
    id: "hyperagent",
    name: "HyperAgent",
    provider: "Hyperbrowser",
    kind: "framework",
    windowGlobals: ["__hyperagent_collectBoundingBoxes", "__hyperagent_collectBoundingBoxesByXPath", "__hyperagent_getScrollableElementXpaths"],
    activeDom: { attributes: ["data-hyperagent-id"] },
    mechanics: { typing: "insert-bulk" },
    confidence: "source",
    sources: ["https://github.com/hyperbrowserai/HyperAgent"],
  },
  {
    id: "magnitude",
    name: "Magnitude",
    provider: "Magnitude",
    kind: "framework",
    windowGlobals: ["__mouseEffectsInitialized", "__typeEffectsInitialized", "__magnitudeShadowDOMAdapterInjected", "__tabActivityTime"],
    activeDom: { ids: ["action-visual-indicator", "type-effects-container"] },
    mechanics: { screens: ["1024x768"] },
    confidence: "source",
    sources: ["https://github.com/magnitudedev/magnitude"],
  },
  {
    id: "anthropic-browser-demo",
    name: "Anthropic browser tooling (main-world refs)",
    provider: "Anthropic",
    kind: "framework",
    windowGlobals: ["__claudeElementMap", "__claudeRefCounter", "__generateAccessibilityTree", "__cdpBrowserRefs"],
    mechanics: { pressMs: [0, 3], typing: "insert-bulk", clickCentre: true, teleports: true },
    confidence: "lab",
    sources: ["https://github.com/anthropics/claude-quickstarts"],
    notes:
      "Anthropic's reference browser-use demo and the Claude desktop app's built-in browser pane inject their element map into the page's main world (observed live on 2026-10-07: __claudeElementMap, __claudeRefCounter, __generateAccessibilityTree after a find/read). Claude in Chrome keeps the same names in an isolated world, invisible to pages. The built-in pane clicks via CDP with pressure 0 and ~1 ms presses and types with one Input.insertText.",
  },
  {
    id: "cloudflare-browser-run",
    name: "Cloudflare Browser Run",
    provider: "Cloudflare",
    kind: "cloud-browser",
    declaredUserAgent: ["CloudflareBrowserRenderingCrawler/"],
    confidence: "docs",
    sources: ["https://developers.cloudflare.com/browser-run/reference/automatic-request-headers"],
    notes: "Adds undeletable cf-brapi-request-id / cf-brapi-devtools headers and signs with Web Bot Auth (server-side).",
  },
  {
    id: "computer-use",
    name: "OS-level computer use",
    provider: "Anthropic / OpenAI reference agents",
    kind: "os-cua",
    mechanics: { hoverMs: [0, 20], pressMs: [0, 20], keyGapMs: [10, 14], typing: "keys", scroll: "wheel-buttons", teleports: true, screens: ["1024x768", "1280x800"] },
    confidence: "source",
    sources: ["https://github.com/anthropics/claude-quickstarts/blob/main/computer-use-demo/computer_use_demo/tools/computer.py"],
    notes: "Anthropic's reference demo runs Firefox ESR on Xvfb 1024×768. xdotool mousemove --sync (single jump), type --delay 12 in 50-character chunks, scroll by wheel-button clicks, ~2 s screenshot pause after every action.",
  },
];
